export const COMPANIES:Record<'CHI'|'BCS', string> = {CHI: 'CHI', BCS: 'BCS'};

export const TABLES:Record<string, string> = {
    AP_Vendor: 'AP_Vendor',
    AR_Customer: 'AR Customer Master',
    AR_CustomerContact: 'AR Customer Contact',
    AR_CustomerCreditCard: 'AR Customer Credit Card',
    AR_CustomerDocumentContacts: 'AR Customer P/L Contacts',
    // AR_CustomerMemo: 'AR Customer Memo',
    AR_CustomerSalesHistory: 'AR Customer Sales History',
    AR_Division: 'AR Division',
    AR_AlternateInvoice: 'AR Alternate Invoice',
    AR_AlternateInvoiceDetail: 'AR Alternate Invoice Detail',
    AR_InvoiceHistoryHeader: 'AR Invoice History Header',
    AR_InvoiceHistoryDetail: 'AR Invoice History Detail',
    AR_InvoiceHistoryTracking: 'AR Invoice History Tracking',
    AR_OpenInvoice: 'AR Open Invoice',
    AR_Salesperson: 'AR Salesperson Master',
    AR_SalespersonCommission: 'AR Salesperson Commission',
    AR_TermsCode: 'AR Terms Code',
    BM_BillHeader: 'Bill of Materials Header',
    BM_BillDetail: 'Bill of Materials Detail',
    BM_BillOptionDetail: 'Bill of Materials Option Detail',
    CI_Item: 'CI Item Master',
    CI_UnitOfMeasure: 'CI Unit of Measure',
    GL_Account: 'GL Account Master',
    GL_PeriodBudgetDetail: 'GL Budget Detail',
    IM_PeriodPostingHistory: 'Period Posting History',
    IM_ItemTransactionHistory : 'Item Transaction History',
    IM_ItemWarehouse: 'Inventory Item Warehouse Detail',
    IM_ItemWhseHistoryByPeriod: 'Item Warehouse History',
    IM_Warehouse: 'Warehouse Codes',
    IM_ItemMemo: 'Item Memo',
    IM_ItemVendor: 'Item Vendor Information',
    IM_ItemCost: 'Inventory Item Cost File',
    IM_Physical: 'IM Physical Inventory',
    IM_PriceCode: 'Inventory Item Price Code File',
    IM_ProductLine: 'Product Line File',
    MP1_WarehouseGroups: 'Warehouse Groups Record',
    MP2_ProjectedDemands: 'Projected Demands',
    MP_04SuppliesAndDemands: 'Supplies And Demands File',
    PO_PurchaseOrderDetail: 'Purchase Order Detail',
    PO_PurchaseOrderHeader: 'Purchase Order Header',
    PR_Employee: 'P/R Employee Master File',
    PR_EmployeeMemo: 'P/R Employee Memo File',
    PR_PayrollHistoryHeader: "P/R Payroll History Header",
    PR_PayrollHistoryDetail: "P/R Payroll History Detail",
    PR_PayrollHistoryWorkersComp: "P/R Payroll History Workers Comp",
    PR_PayrollHistoryWorkersCompDt: "P/R Payroll History Workers Comp Detail",
    SO_CancelReasonCode: 'SO Cancel Reason Code',
    SO_InvoiceHeader: 'SO Invoice Header (Current)',
    SO_SalesOrderDetail: 'SO Sales Order Detail (Current)',
    SO_SalesOrderHeader: 'SO Sales Order Header',
    SO_SalesOrderHistoryHeader: 'SO Sales Order History Header',
    SO_SalesOrderHistoryDetail: 'SO Sales Order History Detail',
    SO_SalesOrderMemo: 'SO Sales Order Memo',
    SO_SalesOrderTierDistribution: 'SO Sales Order Lot/Serial',
    SO_ShipToAddress: 'SO_ShipToAddress',
    SY_Company : 'SY Company Master',
    SY_Country: 'SY Country Master',
    SY_State: 'SY State Master',
    SY_User: 'SY User Master',
    WO1_WorkOrderMaster: 'Work Order Header Record',
    WO2_WorkOrderMaterialDetail: 'Work Order Material Line Detail',
    WO3_WorkOrderOperationDetail: 'Operation (Step) Detail',
    WO9_WorkOrderCostLedger: 'Cost Ledger',
    WOA_WorkCenterMaster: 'Work Center Masterfile',
    WOB_OperationCodeMaster: 'Op Code Masterfile',
    WOC_RoutingMaster: 'Routing Header & Detail Record'
};
